name: Publish Package to npmjs

on:
  workflow_dispatch:
    inputs:
      otp:
        description: 'Enter OTP'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm run build
  
      - run: npm ci

      - run: npm publish --provenance --access public --otp ${{ github.event.inputs.otp }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
